import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/fe4878f0c6.js" crossOrigin="anonymous"></Script>
      </head>
      <body className={`bg-gradient-to-tl from-slate-800 via-violet-500 to-zinc-400 ${inter.className}`}>{children}</body>
    </html>
  );
}
